# -*- coding: utf-8 -*-
"""sahithi_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZ6aNwzLylfONql5IJ_m9bupBCJlCswp
"""

!pip install cohere gtts moviepy python-telegram-bot==13.14

import cohere
from gtts import gTTS
from moviepy.editor import ImageClip, AudioFileClip
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import CallbackContext, CallbackQueryHandler
from telegram.update import Update

co = cohere.Client('msBTuCyK09FRruQx95UAJ3BYKAJEESoshz3f4o8i')

# Define the Cohere response generation function
def generate_response(question):
    response = co.generate(
        model='command-xlarge-nightly',
        prompt=question,
        max_tokens=150
    )
    return response.generations[0].text.strip()

# Define the Text-to-Speech function
def text_to_speech(text, output_file):
    tts = gTTS(text=text, lang='en')
    tts.save(output_file)

# Define the Video Generation function
def generate_video(audio_file, output_file):
    video_clip = ImageClip("sahithi_img.jpg").set_duration(AudioFileClip(audio_file).duration)
    audio_clip = AudioFileClip(audio_file)
    video_clip = video_clip.set_audio(audio_clip)
    video_clip.write_videofile(output_file, codec='libx264', fps=24)

# Main function to handle Telegram messages
def handle_question(update: Update, context: CallbackContext):
    question = update.message.text
    response = generate_response(question)

    audio_file = "response.mp3"
    video_file = "response_video.mp4"

    text_to_speech(response, audio_file)
    generate_video(audio_file, video_file)

    update.message.reply_text("AI Sahithi response: " + response)
    context.bot.send_video(chat_id=update.message.chat_id, video=open(video_file, 'rb'))

def start(update: Update, context: CallbackContext):
    update.message.reply_text("Hello! I am AI Sahithi. How can I assist you today?")

def help_command(update: Update, context: CallbackContext):
    update.message.reply_text("You can ask me any question!")

def unknown(update: Update, context: CallbackContext):
    update.message.reply_text("Sorry, I didn't understand that command.")

# Setup the Telegram bot
updater = Updater("6704753283:AAGQZ0SnvRjpPfXoDqVLtvCFNUI70SKDLwU", use_context=True)
dispatcher = updater.dispatcher

# Add handlers for different commands and messages
dispatcher.add_handler(CommandHandler('start', start))
dispatcher.add_handler(CommandHandler('help', help_command))
dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, handle_question))
dispatcher.add_handler(MessageHandler(Filters.command, unknown))

updater.start_polling()

updater.stop()

